import { describe, expect, it } from "vitest";
import { parseSlideMarkdown } from "../src/parse/index";
import { renderDeckAsync } from "../src/render/index";
import { buildExportCss, KATEX_FONTS_BASE_URL, loadInlineKatexCss } from "../src/render/rich";

describe("rich content rendering", () => {
    it("renders mermaid code fences as SVG diagrams", async () => {
        const deck = parseSlideMarkdown(`\`\`\`mermaid
graph LR
    A --> B
\`\`\`
`);
        const result = await renderDeckAsync(deck);

        expect(result.html).toContain("presenit-mermaid");
        expect(result.html).toMatch(/<svg[\s>]/);
    });

    it("highlights code fences with Shiki", async () => {
        const deck = parseSlideMarkdown(`\`\`\`javascript
const answer = 42;
\`\`\`
`);
        const result = await renderDeckAsync(deck);

        expect(result.html).toContain('class="shiki');
        expect(result.html).toContain("const");
        expect(result.html).toContain("answer");
    });

    it("renders inline and block math with KaTeX", async () => {
        const deck = parseSlideMarkdown(`Inline $E = mc^2$ math.

$$
\\int_0^1 x^2 \\, dx
$$
`);
        const result = await renderDeckAsync(deck);

        expect(result.hasMath).toBe(true);
        expect(result.html).toContain("katex.min.css");
        expect(result.html).toContain('class="katex"');
        expect(result.html).toContain("katex-display");
        // Must be generated by our direct katex@0.18 dependency (npm consumers
        // never inherit workspace overrides that previously papered over this).
        expect(result.html).toContain("katex-sizing");
        expect(result.html).not.toMatch(/class="sizing /);
        expect(result.css).toContain("katex@0.18.1");
    });

    it("inlines local KaTeX CSS with CDN font URLs for export", async () => {
        const css = await loadInlineKatexCss();
        expect(css).toContain(".katex");
        expect(css).toContain(KATEX_FONTS_BASE_URL);
        expect(css).not.toMatch(/url\(fonts\//);
    });

    it("buildExportCss replaces @import with inline KaTeX and print overrides", async () => {
        const deck = parseSlideMarkdown(`Inline $x$ math.`);
        const result = await renderDeckAsync(deck);
        const exportCss = await buildExportCss(result.css);

        expect(exportCss).not.toMatch(/@import\s+url\(["']?[^"']*katex/i);
        expect(exportCss).toContain(".katex .katex-mathml");
        expect(exportCss).toContain("display: none");
        expect(exportCss).toContain(KATEX_FONTS_BASE_URL);
    });
});
