import type { JSX } from "preact";
import { useLayoutEffect, useEffect, useRef, useState } from "preact/hooks";
import { applyRevealVisibility } from "./store";

export type SlideFrameLaser = {
    active: boolean;
    dot: { x: number; y: number } | null;
    onMove?: (x: number, y: number) => void;
    onLeave?: () => void;
    hideCursor?: boolean;
};

type Props = {
    html: string;
    width: number;
    height: number;
    className?: string;
    laser?: SlideFrameLaser;
    /** Current reveal counter; fragments with at<=step are shown. */
    revealStep?: number;
    /** Overview / PDF: show every fragment. */
    revealShowAll?: boolean;
    /** CSS var for fragment fade duration (seconds). */
    animDuration?: number;
};

/**
 * Scale a fixed-size slide to fit its container (contain).
 */
export function SlideFrame({
    html,
    width,
    height,
    className,
    laser,
    revealStep = 0,
    revealShowAll = false,
    animDuration,
}: Props): JSX.Element {
    const viewportRef = useRef<HTMLDivElement>(null);
    const scalerRef = useRef<HTMLDivElement>(null);
    const canvasRef = useRef<HTMLDivElement>(null);
    const [scale, setScale] = useState(1);

    const onLaserPointerMove = (event: PointerEvent) => {
        if (!laser?.active || !laser.onMove) {
            return;
        }
        const el = scalerRef.current;
        if (!el) {
            return;
        }
        const rect = el.getBoundingClientRect();
        if (rect.width <= 0 || rect.height <= 0) {
            return;
        }
        const x = (event.clientX - rect.left) / rect.width;
        const y = (event.clientY - rect.top) / rect.height;
        if (x < 0 || x > 1 || y < 0 || y > 1) {
            return;
        }
        laser.onMove(x, y);
    };

    const onLaserPointerLeave = () => {
        if (!laser?.active || !laser.onLeave) {
            return;
        }
        laser.onLeave();
    };

    useEffect(() => {
        const el = viewportRef.current;
        if (!el) {
            return;
        }

        const update = () => {
            const rect = el.getBoundingClientRect();
            const next = Math.min(rect.width / width, rect.height / height);
            setScale(Number.isFinite(next) && next > 0 ? next : 1);
        };

        update();
        const observer = new ResizeObserver(update);
        observer.observe(el);
        return () => observer.disconnect();
    }, [width, height]);

    useLayoutEffect(() => {
        applyRevealVisibility(canvasRef.current, revealStep, revealShowAll);
    }, [html, revealStep, revealShowAll]);

    const animStyle =
        animDuration !== undefined
            ? ({ "--presenit-anim-duration": `${animDuration}s` } as Record<string, string>)
            : undefined;

    return (
        <div ref={viewportRef} class={`slide-frame ${className ?? ""}`} style={animStyle}>
            <div
                ref={scalerRef}
                class={`slide-frame__scaler${laser?.active && laser.hideCursor ? " slide-frame__scaler--laser" : ""}`}
                style={{
                    width: `${width * scale}px`,
                    height: `${height * scale}px`,
                }}
                onPointerMove={onLaserPointerMove}
                onPointerLeave={onLaserPointerLeave}
            >
                <div
                    ref={canvasRef}
                    class="slide-frame__canvas"
                    style={{
                        width: `${width}px`,
                        height: `${height}px`,
                        transform: `scale(${scale})`,
                    }}
                    // Slide HTML is generated by our renderer.
                    dangerouslySetInnerHTML={{ __html: html }}
                />
                {laser?.active && laser.dot ? (
                    <div
                        class="laser-dot"
                        style={{
                            left: `${laser.dot.x * 100}%`,
                            top: `${laser.dot.y * 100}%`,
                        }}
                    />
                ) : null}
            </div>
        </div>
    );
}
