import type { JSX } from "preact";
import { useEffect, useRef, useState } from "preact/hooks";

type Props = {
    html: string;
    width: number;
    height: number;
    className?: string;
};

/**
 * Scale a fixed-size slide to fit its container (contain).
 */
export function SlideFrame({ html, width, height, className }: Props): JSX.Element {
    const viewportRef = useRef<HTMLDivElement>(null);
    const [scale, setScale] = useState(1);

    useEffect(() => {
        const el = viewportRef.current;
        if (!el) {
            return;
        }

        const update = () => {
            const rect = el.getBoundingClientRect();
            const next = Math.min(rect.width / width, rect.height / height);
            setScale(Number.isFinite(next) && next > 0 ? next : 1);
        };

        update();
        const observer = new ResizeObserver(update);
        observer.observe(el);
        return () => observer.disconnect();
    }, [width, height]);

    return (
        <div ref={viewportRef} class={`slide-frame ${className ?? ""}`}>
            <div
                class="slide-frame__scaler"
                style={{
                    width: `${width * scale}px`,
                    height: `${height * scale}px`,
                }}
            >
                <div
                    class="slide-frame__canvas"
                    style={{
                        width: `${width}px`,
                        height: `${height}px`,
                        transform: `scale(${scale})`,
                    }}
                    // Slide HTML is generated by our renderer.
                    dangerouslySetInnerHTML={{ __html: html }}
                />
            </div>
        </div>
    );
}
